name: Build
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  Bbuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: KengoTODA/setup-java@vintroduce-cache
      with:
        java-version: '12.x'
        distribution: 'adopt'
        cache: gradle

    - name: Setup flutter
      uses: subosito/flutter-action@master
      with:
        flutter-version: 2.0.3
        channel: 'any'
    - name: pub get
      run: flutter pub get

    - name: Build project
      run: flutter build